//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class abastecimentos
    {
        public int id_abastecimento { get; set; }
        public string data_abastecimento { get; set; }
        public string tipo_combustivel { get; set; }
        public string posto { get; set; }
        public string placa { get; set; }
        public string valor_litro { get; set; }
        public string valor_total { get; set; }
        public string litros { get; set; }
    }
}
