//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class abastecimentos
    {
        public int id_abastecimento { get; set; }
        public string data_abastecimento { get; set; }
        public string tipo_combustivel { get; set; }
        public string posto { get; set; }
        public string placa { get; set; }
        public string valor_litro { get; set; }
        public string valor_total { get; set; }
        public string litros { get; set; }
    }
}
