//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluguel_veiculos
    {
        public int id_aluguel { get; set; }
        public string cpf { get; set; }
        public string numero_veiculos { get; set; }
        public string data_inicio { get; set; }
        public string data_entrega { get; set; }
    }
}
