//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluguel_veiculos
    {
        public int id_aluguel { get; set; }
        public string cpf { get; set; }
        public string numero_veiculos { get; set; }
        public string data_inicio { get; set; }
        public string data_entrega { get; set; }
    }
}
