//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entradas
    {
        public int id_entrada { get; set; }
        public string data_entrada { get; set; }
        public string placa { get; set; }
        public string cpf { get; set; }
        public string horario_entrada { get; set; }
    }
}
