//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estoque_peca
    {
        public int id_peca { get; set; }
        public string tipo { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string quantidade { get; set; }
        public string valor_unitario { get; set; }
        public string nome_veiculo { get; set; }
    }
}
