//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estoque_peca
    {
        public int id_peca { get; set; }
        public string tipo { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string quantidade { get; set; }
        public string valor_unitario { get; set; }
        public string nome_veiculo { get; set; }
    }
}
