//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manutencoes
    {
        public int id_manutencao { get; set; }
        public string data_manutencao { get; set; }
        public string motivo { get; set; }
        public string estabelecimento { get; set; }
        public string placa { get; set; }
        public string valor_total { get; set; }
    }
}
