//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbControleFrotasEntities : DbContext
    {
        public dbControleFrotasEntities()
            : base("name=dbControleFrotasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<abastecimentos> abastecimentos { get; set; }
        public DbSet<aluguel_veiculos> aluguel_veiculos { get; set; }
        public DbSet<entradas> entradas { get; set; }
        public DbSet<estoque_peca> estoque_peca { get; set; }
        public DbSet<login> login { get; set; }
        public DbSet<manutencoes> manutencoes { get; set; }
        public DbSet<motoristas> motoristas { get; set; }
        public DbSet<multas> multas { get; set; }
        public DbSet<pneus> pneus { get; set; }
        public DbSet<quilometragem> quilometragem { get; set; }
        public DbSet<saidas> saidas { get; set; }
        public DbSet<seguros> seguros { get; set; }
        public DbSet<sinistros> sinistros { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
        public DbSet<veiculos> veiculos { get; set; }
        public DbSet<viagens> viagens { get; set; }
    }
}
