//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<motoristas> motoristas { get; set; }
        public DbSet<abastecimentos> abastecimentos { get; set; }
        public DbSet<aluguel_veiculos> aluguel_veiculos { get; set; }
        public DbSet<entradas> entradas { get; set; }
        public DbSet<estoque_peca> estoque_peca { get; set; }
        public DbSet<login> login { get; set; }
        public DbSet<manutencoes> manutencoes { get; set; }
        public DbSet<multas> multas { get; set; }
        public DbSet<pneus> pneus { get; set; }
        public DbSet<quilometragem> quilometragem { get; set; }
        public DbSet<saidas> saidas { get; set; }
        public DbSet<seguros> seguros { get; set; }
        public DbSet<sinistros> sinistros { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
        public DbSet<veiculos> veiculos { get; set; }
        public DbSet<viagens> viagens { get; set; }
    }
}
