//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class motoristas
    {
        public int id_motorista { get; set; }
        public string nome_completo { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
        public string cnh { get; set; }
        public string vencimento_cnh { get; set; }
        public string empresa { get; set; }
    }
}
