//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class multas
    {
        public int id_multa { get; set; }
        public string data_multa { get; set; }
        public string auto_infracao { get; set; }
        public string descricao_infracao { get; set; }
        public string local_multa { get; set; }
        public string data_vencimento { get; set; }
        public string data_pagamento { get; set; }
        public string situacao { get; set; }
        public string placa { get; set; }
        public string cpf { get; set; }
        public string valor { get; set; }
        public string gravidade { get; set; }
    }
}
