//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class multas
    {
        public int id_multa { get; set; }
        public string data_multa { get; set; }
        public string auto_infracao { get; set; }
        public string descricao_infracao { get; set; }
        public string local_multa { get; set; }
        public string data_vencimento { get; set; }
        public string data_pagamento { get; set; }
        public string situacao { get; set; }
        public string placa { get; set; }
        public string cpf { get; set; }
        public string valor { get; set; }
        public string gravidade { get; set; }
    }
}
