//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pneus
    {
        public int id_pneu { get; set; }
        public string numero_serie { get; set; }
        public string situacao { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string dimensao { get; set; }
        public string placa { get; set; }
    }
}
