//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pneus
    {
        public int id_pneu { get; set; }
        public string numero_serie { get; set; }
        public string situacao { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string dimensao { get; set; }
        public string placa { get; set; }
    }
}
