//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quilometragem
    {
        public int id_quilometragem { get; set; }
        public string data_inicio { get; set; }
        public string data_atual { get; set; }
        public string placa { get; set; }
        public string quilometros_rodados { get; set; }
    }
}
