//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguros
    {
        public int id_seguro { get; set; }
        public string numero_apolice { get; set; }
        public string seguradora { get; set; }
        public string segurado { get; set; }
        public string corretor { get; set; }
        public string data_inicio { get; set; }
        public string data_vencimento { get; set; }
        public decimal valor_total { get; set; }
        public decimal numero_parcelas { get; set; }
        public string situacao { get; set; }
        public string placa { get; set; }
    }
}
