//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguros
    {
        public int id_seguro { get; set; }
        public string numero_apolice { get; set; }
        public string seguradora { get; set; }
        public string segurado { get; set; }
        public string corretor { get; set; }
        public string data_inicio { get; set; }
        public string data_vencimento { get; set; }
        public decimal valor_total { get; set; }
        public decimal numero_parcelas { get; set; }
        public string situacao { get; set; }
        public string placa_seguro { get; set; }
    }
}
