//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinistros
    {
        public int id_sinistro { get; set; }
        public string data_sinistro { get; set; }
        public string descricao_ocorrido { get; set; }
        public string local_sinistro { get; set; }
        public string placa { get; set; }
        public string cpf { get; set; }
    }
}
