//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFrota.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viagens
    {
        public int id_viagem { get; set; }
        public string data_viagem { get; set; }
        public string data_entregar { get; set; }
        public string data_entregue { get; set; }
        public string motivo { get; set; }
        public string situacao { get; set; }
        public decimal km_inicial { get; set; }
        public decimal km_final { get; set; }
        public string placa { get; set; }
        public string cpf { get; set; }
    }
}
